# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.5

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

after_success: codecov

deploy:

  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6
