# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.5

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

after_success: codecov
